lsi: false
safe: true
source: / 
remote_theme: jekyll/minima
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jemoji
minima:
  skin: dark
  date_format: "%Y-%m-%d"
  header_pages:
    - about.md
  social_links:
    github: luxetobscura