lsi: false
safe: true
source: / 
remote_theme: jekyll/minima
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
minima:
  skin: dark
  social_links:
    github: luxetobscura